name: JUnit (MC 1.19.4-1.20.4)

on:
    push:
        branches:
            - 'feature/**'
    pull_request:

jobs:
    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: validate gradle wrapper
              uses: gradle/wrapper-validation-action@v2
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'adopt'
                  cache: gradle
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build Skript and run JUnit
              run: ./gradlew clean JUnitJava17
            - name: Upload JUnit Test Results
              uses: actions/upload-artifact@v3
              with:
                  name: "Skript"
                  path: "bin/*"
